# Generated by Django 4.1 on 2023-04-28 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheetentry",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 28, 10, 19, 59, 188088, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
