# Generated by Django 4.1 on 2023-04-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chore", "0003_alter_timesheetentry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileinfo",
            name="portfolio_site",
        ),
    ]
